'use strict';
const fs=require('fs'), crypto=require('crypto'), path=require('path');
const DISK=process.env.BRAINK_DISK||'/mnt/data/BRAINK_MACHINE_001_R8.vdisk';
const DISK_BYTES=64*1024*1024; // physically materialised virtual disk for this proof specimen
const BLOCK=4096, SUPER=0, ROOT=256*BLOCK; // root at 1 MiB
const ZEROLESS=[-3,-2,1,2,3];
function sha(b){return crypto.createHash('sha256').update(b).digest('hex')}
function canon(o){return Buffer.from(JSON.stringify(o,Object.keys(o).sort()))}
function writeBlock(fd,off,obj){let b=Buffer.from(JSON.stringify(obj)); if(b.length>BLOCK-8) throw Error('E_BLOCK_TOO_LARGE'); let out=Buffer.alloc(BLOCK); out.writeUInt32BE(b.length,0); b.copy(out,8); fs.writeSync(fd,out,0,out.length,off); return sha(b)}
function readBlock(fd,off){let h=Buffer.alloc(8); fs.readSync(fd,h,0,8,off); let n=h.readUInt32BE(0); if(!n||n>BLOCK-8) return null; let b=Buffer.alloc(n); fs.readSync(fd,b,0,n,off+8); return {obj:JSON.parse(b.toString()),bytes:b,sha256:sha(b)}}
function init(){let fd=fs.openSync(DISK,'w+'); fs.ftruncateSync(fd,DISK_BYTES); let machine={schema:'kex.braink.machine.r8',machine_id:'KEX-MACHINE-001',contract:'machine://kex/hardware-contract',controller:'KEX_STORAGE_CONTROLLER',storage_address:'device://storage/block0',disk_bytes:DISK_BYTES,block_bytes:BLOCK,blocks:DISK_BYTES/BLOCK,zero_less_geometry:ZEROLESS,state:'LAUNCHED_NO_BRAINK',braink_root_lba:null,braink_root_sha256:null}; writeBlock(fd,SUPER,machine); fs.fsyncSync(fd); fs.closeSync(fd); console.log(JSON.stringify({action:'LAUNCH',disk:DISK,...machine},null,2));}
function enter(){let fd=fs.openSync(DISK,'r'); let s=readBlock(fd,SUPER); fs.closeSync(fd); if(!s) throw Error('E_NO_SUPERBLOCK'); console.log(JSON.stringify({action:'ENTER_MACHINE',superblock:s.obj,superblock_sha256:s.sha256},null,2));}
function install(){let fd=fs.openSync(DISK,'r+'); let s=readBlock(fd,SUPER); if(!s) throw Error('E_NO_SUPERBLOCK'); let root={schema:'braink.root.r8',braink_id:'BRAINK::KEX-MACHINE-001::R8',machine_id:s.obj.machine_id,lineage_root:'BRAINK::LINEAGE::KEX-MACHINE-001::GENESIS',observer_root:'OBS://BRAINK/KEX-MACHINE-001/R8',network_root:'LEX://BRAINK/KEX-MACHINE-001',vector_root:'VEC://MACHINE/KEX-MACHINE-001/LOCAL',medium_root:'DEVICE://KEX-MACHINE-001/STORAGE/BLOCK0',controller_root:'KEX_STORAGE_CONTROLLER://KEX-MACHINE-001',storage_root:'KEX://MACHINE/KEX-MACHINE-001/STORAGE/',vfs_root:'KEX://VFS/KEX-MACHINE-001/',vfs_role:'RESOLVER_ONLY',proof_root:'PROOF://BRAINK/KEX-MACHINE-001/R8',zero_less_geometry:ZEROLESS,installed_state:'RESIDENT'}; let rh=writeBlock(fd,ROOT,root); s.obj.state='BRAINK_RESIDENT'; s.obj.braink_root_lba=256; s.obj.braink_root_sha256=rh; s.obj.braink_id=root.braink_id; let sh=writeBlock(fd,SUPER,s.obj); fs.fsyncSync(fd); fs.closeSync(fd); console.log(JSON.stringify({action:'INSTALL_BRAINK',root_offset:ROOT,root_lba:256,braink_root_sha256:rh,superblock_sha256:sh,root},null,2));}
function bootverify(){let fd=fs.openSync(DISK,'r'); let s=readBlock(fd,SUPER); if(!s) throw Error('E_NO_SUPERBLOCK'); if(s.obj.state!=='BRAINK_RESIDENT') throw Error('E_BRAINK_NOT_REGISTERED'); let r=readBlock(fd,s.obj.braink_root_lba*BLOCK); fs.closeSync(fd); if(!r) throw Error('E_BRAINK_ROOT_MISSING'); let checks={hash_match:r.sha256===s.obj.braink_root_sha256,machine_match:r.obj.machine_id===s.obj.machine_id,braink_match:r.obj.braink_id===s.obj.braink_id,lineage_present:!!r.obj.lineage_root,medium_present:!!r.obj.medium_root,controller_present:!!r.obj.controller_root,vfs_present:!!r.obj.vfs_root,vfs_resolver_only:r.obj.vfs_role==='RESOLVER_ONLY',network_present:!!r.obj.network_root,observer_present:!!r.obj.observer_root}; let pass=Object.values(checks).every(Boolean); let receipt={action:'REBOOT_DISCOVER_VERIFY',process_pid:process.pid,disk:DISK,superblock_sha256:s.sha256,braink_root_sha256:r.sha256,checks,status:pass?'PASS':'FAIL',discovered_braink:r.obj}; console.log(JSON.stringify(receipt,null,2)); if(!pass) process.exit(2); fs.writeFileSync('/mnt/data/BRAINK_MACHINE_001_R8_BOOT_RECEIPT.json',JSON.stringify(receipt,null,2));}
let cmd=process.argv[2]; if(cmd==='init')init(); else if(cmd==='enter')enter(); else if(cmd==='install')install(); else if(cmd==='boot-verify')bootverify(); else throw Error('use init|enter|install|boot-verify');
