#!/bin/bash
# Regenerate every evidence artefact in evidence/ by actually executing the code.
#
# Order matters: the package manifest is written last so that it hashes the
# freshly generated receipts. The manifest deliberately excludes itself.
set -euo pipefail

PACKAGE_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$PACKAGE_ROOT"

PYTHON="${PYTHON:-python3}"
export PYTHONPATH="$PACKAGE_ROOT/src${PYTHONPATH:+:$PYTHONPATH}"

echo "== BrAInK runtime :: evidence generation =="
echo "package root : $PACKAGE_ROOT"
mkdir -p evidence

echo
echo "-- 1/5 test results (real pytest run) --"
set +e
"$PYTHON" -m pytest tests/ -v --tb=short > evidence/.pytest_output.txt 2>&1
PYTEST_EXIT=$?
set -e
tail -n 3 evidence/.pytest_output.txt

"$PYTHON" - "$PYTEST_EXIT" <<'PY'
import json
import re
import sys

exit_code = int(sys.argv[1])
raw = open("evidence/.pytest_output.txt", encoding="utf-8", errors="replace").read()

names = re.findall(r"^(tests/\S+::.+?)\s+(PASSED|FAILED|ERROR|SKIPPED|XFAIL|XPASS)\b", raw, re.M)
passed = sum(1 for _, s in names if s == "PASSED")
failed = sum(1 for _, s in names if s == "FAILED")
errors = sum(1 for _, s in names if s == "ERROR")

summary_lines = [ln.strip() for ln in raw.strip().splitlines() if re.search(r"\d+ (passed|failed|error)", ln)]
summary = summary_lines[-1] if summary_lines else raw.strip().splitlines()[-1]

from braink_runtime.receipts import generate_test_results

result = generate_test_results(
    passed=passed,
    failed=failed,
    errors=errors,
    test_names=[n for n, _ in names],
    raw_summary=summary,
)
result["pytest_exit_code"] = exit_code
result["command"] = "python -m pytest tests/ -v --tb=short"
if exit_code != 0:
    result["status"] = "FAILED"

with open("evidence/TEST_RESULTS.json", "w", encoding="utf-8") as handle:
    json.dump(result, handle, indent=2, sort_keys=True)
print("  status:", result["status"], "| tests:", result["tests_run"])
PY
rm -f evidence/.pytest_output.txt

echo
echo "-- 2/5 ledger integrity receipt --"
"$PYTHON" - <<'PY'
import json
import os
import shutil
import tempfile

from braink_runtime.ledger import Ledger

workspace = tempfile.mkdtemp(prefix="braink-evidence-ledger-")
try:
    ledger = Ledger(os.path.join(workspace, "ledger.sqlite"))
    ledger.append("RUNTIME_START", {"source": "generate_receipt.command"})
    ledger.append("COMMAND", {"intent": "VERIFY", "tokens": ["verify", "ledger"]})
    ledger.append("RUNTIME_SHUTDOWN", {"clean": True})
    receipt = ledger.export_receipt()
    ledger.close()
    receipt["ledger_path"] = "<ephemeral temp ledger>"
    receipt["note"] = "Generated by scripts/generate_receipt.command against a fresh ephemeral ledger."
    with open("evidence/LEDGER_INTEGRITY_RECEIPT.json", "w", encoding="utf-8") as handle:
        json.dump(receipt, handle, indent=2, sort_keys=True)
    print("  entries:", receipt["entry_count"], "| chain_valid:", receipt["chain_valid"])
finally:
    shutil.rmtree(workspace, ignore_errors=True)
PY

echo
echo "-- 3/5 restart receipt --"
"$PYTHON" - <<'PY'
import json
import os
import shutil
import tempfile

from braink_runtime.ledger import Ledger
from braink_runtime.restart import RestartManager
from braink_runtime.runtime import BrAInKRuntime

workspace = tempfile.mkdtemp(prefix="braink-evidence-restart-")
ledger_path = os.path.join(workspace, "ledger.sqlite")
state_path = os.path.join(workspace, "restart_state.json")
try:
    runtime = BrAInKRuntime(
        {"ledger_path": ledger_path, "state_path": state_path, "session_id": "evidence-session"}
    )
    runtime.start()
    runtime.process_command("run diagnostics")
    manager = RestartManager(state_path, ledger_path, session_id="evidence-session")
    manager.save_state(runtime.ledger, clean=True)
    manager.simulate_unclean_shutdown(runtime.ledger)
    runtime.ledger.close()

    reopened = Ledger(ledger_path)
    receipt = manager.generate_restart_receipt(reopened, manager.load_state())
    reopened.close()
    receipt["ledger_path"] = "<ephemeral temp ledger>"
    receipt["state_path"] = "<ephemeral temp state>"
    receipt["note"] = "Ledger reopened in a new object after a simulated unclean shutdown; chain re-verified."
    with open("evidence/RESTART_RECEIPT.json", "w", encoding="utf-8") as handle:
        json.dump(receipt, handle, indent=2, sort_keys=True)
    print("  continuity_proven:", receipt["continuity_proven"], "| status:", receipt["status"])
finally:
    shutil.rmtree(workspace, ignore_errors=True)
PY

echo
echo "-- 4/5 DNS proof receipt (status capped at LOCALLY_EXECUTED) --"
"$PYTHON" - <<'PY'
import json
import os

from braink_runtime.dns_transport import DNSTransport, build_query

name = os.environ.get("BRAINK_DNS_QUERY_NAME", "example.com")
rtype = os.environ.get("BRAINK_DNS_RECORD_TYPE", "A")
resolver = os.environ.get("BRAINK_DNS_RESOLVER", "8.8.8.8")

transport = DNSTransport()
receipt = transport.generate_proof_receipt(name, rtype, resolver).to_dict()
_, wire = build_query(name, rtype, txid=0x4242)
receipt["query_wire_hex"] = wire.hex()
receipt["query_wire_length"] = len(wire)
receipt["transport_status"] = transport.last_status
receipt["transport_error"] = transport.last_error
receipt["response_meta"] = transport.last_response_meta
receipt["status"] = "LOCALLY_EXECUTED"
receipt["local_execution_result"] = transport.last_status
receipt["authoritative"] = False
receipt["authoritative_external_confirmed"] = False
receipt["note"] = (
    "Authoritative DNS not confirmed from sandbox - capped at LOCALLY_EXECUTED per Rule 3"
)
receipt["status_explanation"] = (
    "status=LOCALLY_EXECUTED records that the query was built and transmitted from this "
    "host. local_execution_result records whether a parsable response came back; a value "
    "of LOCAL_EXECUTION_FAILED means the sandbox has no DNS egress. Neither value ever "
    "implies external observation."
)
with open("evidence/DNS_PROOF_RECEIPT.json", "w", encoding="utf-8") as handle:
    json.dump(receipt, handle, indent=2, sort_keys=True)
print("  status:", receipt["status"], "| transport:", receipt["transport_status"])
PY

echo
echo "-- 5/5 package manifest --"
rm -f evidence/PACKAGE_MANIFEST.json
"$PYTHON" - <<'PY'
import json

from braink_runtime.receipts import generate_package_manifest

manifest = generate_package_manifest(".")
manifest["note"] = (
    "Manifest excludes itself, caches and compiled artefacts. Regenerate with "
    "scripts/generate_receipt.command after any change."
)
with open("evidence/PACKAGE_MANIFEST.json", "w", encoding="utf-8") as handle:
    json.dump(manifest, handle, indent=2, sort_keys=True)
print("  files:", manifest["file_count"], "| manifest_hash:", manifest["manifest_hash"][:16])
PY

echo
echo "evidence written to $PACKAGE_ROOT/evidence"
exit $PYTEST_EXIT
