#!/usr/bin/env python3
from __future__ import annotations
import json, pathlib, html, hashlib
ROOT=pathlib.Path(__file__).resolve().parent
M=json.loads((ROOT/'BRAINK_PUBLIC_CORPORATE_RELEASE.json').read_text())
OUT=ROOT/'dist'; OUT.mkdir(exist_ok=True)
COPY={
'braink.com.au':('BRAINK. Intelligence you can operate.','BRAINK AI · User Runtime','A governed AI environment that preserves semantic identity, continuation, evidence and user control across workspaces, applications and server-room runtimes.'),
'braink-intelligence.com.au':('Intelligence with lineage.','BRAINK Intelligence · Research · Enterprise','A professional intelligence surface for research, analysis, enterprise workflows and evidence-led decisions, grounded in BRAINK, KEX and IL-LLM.'),
'braink-learning.com.au':('Learning that keeps its context.','BRAINK Learning · Guided Knowledge','A learning environment where definitions, relations, observer state and continuation remain addressable as users learn, explore and build.')}
T='''<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>{title}</title><meta name="description" content="{lead}"><style>:root{{--bg:#071019;--ink:#f7fbff;--muted:#a8bac8;--line:#1d3445;--accent:#8de7ff}}*{{box-sizing:border-box}}body{{margin:0;font:16px/1.55 system-ui;background:radial-gradient(circle at 20% 0,#10263a 0,transparent 34%),var(--bg);color:var(--ink)}}a{{color:inherit}}.w{{max-width:1180px;margin:auto;padding:0 28px}}nav{{display:flex;justify-content:space-between;padding:24px 0;border-bottom:1px solid var(--line)}}.brand{{font-weight:800;letter-spacing:.12em}}.tag{{font-size:12px;color:var(--accent);text-transform:uppercase;letter-spacing:.16em}}main{{padding:90px 0}}h1{{font-size:clamp(48px,8vw,92px);line-height:.95;letter-spacing:-.055em;margin:12px 0 28px}}p{{color:var(--muted);max-width:760px;font-size:20px}}.grid{{display:grid;grid-template-columns:repeat(3,1fr);gap:18px;margin-top:50px}}article{{border:1px solid var(--line);padding:25px;border-radius:18px;background:#0b1721}}button,.button{{display:inline-block;background:var(--ink);color:#071019;padding:14px 20px;border-radius:12px;text-decoration:none;font-weight:750;border:0}}@media(max-width:800px){{.grid{{grid-template-columns:1fr}}}}</style></head><body><div class="w"><nav><div><div class="brand">BRAINK</div><div class="tag">{domain}</div></div><div>KEDDEH Systems</div></nav><main><div class="tag">{kicker}</div><h1>{title}</h1><p>{lead}</p><p><a class="button" href="/auth/google/start?domain={domain}">Continue with Google</a></p><section class="grid"><article><h3>Governed corpus</h3><p>IL-LLM semantic identity, definitions, relations, observer state and continuation remain attributable.</p></article><article><h3>Resident runtime</h3><p>BRAINK orchestration, KEX execution, VFS workspaces and KEDDEH server-room mesh remain bound to this surface.</p></article><article><h3>Secure rails</h3><p>Google OAuth and Stripe operate through dedicated server processes. Site code never owns provider secret material.</p></article></section><p><button onclick="fetch('/payments/checkout',{{method:'POST',headers:{{'content-type':'application/json'}},body:JSON.stringify({{domain:'{domain}',product:'BRAINK'}})}}).then(r=>r.json()).then(x=>x.checkout_url?location.href=x.checkout_url:alert(x.error||x.status))">Start securely</button></p></main></div></body></html>'''
readback={'schema':'kex.braink.site-build.v1','domains':{},'overall':True}
for d,spec in M['domains'].items():
    title,kicker,lead=COPY[d]; p=OUT/d; p.mkdir(parents=True,exist_ok=True); f=p/'index.html'
    f.write_text(T.format(domain=html.escape(d),title=html.escape(title),kicker=html.escape(kicker),lead=html.escape(lead)))
    readback['domains'][d]={'site':spec['site'],'runtime':spec['runtime'],'workspace':spec['workspace'],'vfs':spec['vfs'],'sha256':hashlib.sha256(f.read_bytes()).hexdigest(),'status':'BUILT'}
(ROOT/'SITE_BUILD_READBACK.json').write_text(json.dumps(readback,indent=2)); print(json.dumps(readback,indent=2))
